### ISSUE TITLE
Update Documentation in Conformance to the Documentation Guide

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziQuestionnaire#10]
### Problem

The current documentation in the module provides a good overview of the API and includes documentation for most public APIs. In line with the newly published [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md), we should update the documentation in accordance with the guidelines.

### Solution

The documentation should be updated to provide more insightful inline documentation, improve the README file and the DocC landing page in conformance with the [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).

- [x] Update inline documentation, including links and other elements noted in the [Code Documentation section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#code-documentation).
- [x] Improve the DocC landing page as detailed in the [Landing Page section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#landing-page).
- [x] Add a graphic and visual representation of the module user interface (UI) or UML diagram of the architecture or interacting with the module API.
- [x] Improve the READMe as noted in the [README section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#readme).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Chizobaonorh** [comment]
Hello @PSchmiedmayer i want to contribute to this documentation, how do i get started doing that?

**Comment by PSchmiedmayer** [comment]
Hi @Chizobaonorh,
It's great to hear that you are interested in contributing to the documentation! The best way to get started would be to follow the different links in the issue above and take a look at the links that are provided in the [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).
Documentation for this repo uses the DocC tooling; there are multiple videos and starting tutorials linked in the [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).

It would also be beneficial if you are familiar with Swift to get started; I recommend looking at our getting started instructions in our CS342 organization: https://github.com/orgs/CS342/discussions/3. To create screenshots, explore the API, and ensure you have a comprehensive overview, you must install Xcode as described in the CS342 announcement.

**Comment by Chizobaonorh** [comment]
Okay thank you very much. I just did a research on this Xcode, and from the information gathered it is a tool for building apps, as a technical writer what would i be needing this for?

**Comment by PSchmiedmayer** [comment]
@Chizobaonorh Yes, Xcode is used for development, but also enables you to more easily work on the documentation as it provides syntax highlighting and a way to run the software to generate screenshots. I would recommend having a way to play around with the source code, understand, and run it as a good prerequisite to improving the overall documentation of the module. Let us know if you run into any issues or need any additional support, we are thankful for any contribution! 👍

**Comment by Chizobaonorh** [comment]
I am not sure i might be able to help out with this, because i really do not have knowledge on swift and xcode yet.

**Comment by PSchmiedmayer** [comment]
That makes sense; thank you for reaching out! Let us know once you have gained more experience or if you want to get started with an other good first issue in any other of our projects.

**Comment by Chizobaonorh** [comment]
There is another issue i can contribute to?
