### ISSUE TITLE
Six minute walk distance test

### ISSUE THREAD

**Issue by scdi** [StanfordSpezi/SpeziQuestionnaire#20]
### Problem

The six minute walk distance test sample result is not implemented for FHIR in Spezi. How do we go about implementing it?

### Solution

We could be provided a way to implement samples that are not yet implemented or the HealthKit module could have it ready to be collected as is the case for heart rate as an example.

### Additional context

The six minute walk distance test is gathered passively and is a great meausre of cardiac health. It is a needed information for monitoring cardiac health.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@scdi I have moved this issue to Spezi Questionnaire as we have started to implement a six minute walk test in here which is currently in process and found at https://github.com/StanfordSpezi/SpeziQuestionnaire/pull/16.

If you are just looking for the HealthKit HKSample to FHIR mapping please check out https://github.com/StanfordBDHG/HealthKitOnFHIR and maybe create an issue over there.

**Comment by scdi** [comment]
Thank you!

**Comment by vishnuravi** [comment]
This issue was addresed by #16, which has been merged into the main branch - will close.
